# -*- coding: utf-8 -*-
"""artificial_intelligence_task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t51ZsJdjGbUk4pWa0KuQWHtKjrSp6yKF
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

data = {
    'title': ['Inception', 'Interstellar', 'The Dark Knight', 'Toy Story', 'Wall-E', 'Finding Nemo'],
    'genre': ['Sci-Fi Thriller', 'Sci-Fi Drama', 'Action Crime', 'Animation Comedy', 'Animation Sci-Fi', 'Animation Family']
}

df = pd.DataFrame(data)
df

tfidf = TfidfVectorizer(stop_words='english')
genre_matrix = tfidf.fit_transform(df['genre'])

similarity = cosine_similarity(genre_matrix)

def recommend_movie(movie_name):
    if movie_name not in df['title'].values:
        return "Movie not found!"

    idx = df[df['title'] == movie_name].index[0]
    scores = list(enumerate(similarity[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    recommended = []
    for i in scores[1:4]:
        recommended.append(df.iloc[i[0]]['title'])

    return recommended

recommend_movie("Inception")