# -*- coding: utf-8 -*-
"""artificial_intelligence_task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCFzJvsPB6MOWofA8hR7VadCGvROITnS
"""

# Simple Rule-Based Chatbot

def chatbot_response(user_input):
    user_input = user_input.lower()

    # Greetings
    if "hello" in user_input or "hi" in user_input:
        return "Hello! How can I help you today?"

    # Asking about chatbot
    elif "who are you" in user_input:
        return "I'm a simple rule-based chatbot created in Python!"

    # Asking about weather
    elif "weather" in user_input:
        return "I can't check live weather yet, but it looks sunny in my code!"

    # Asking about time
    elif "time" in user_input:
        from datetime import datetime
        return f"The current time is {datetime.now().strftime('%H:%M:%S')}"

    # Asking for help
    elif "help" in user_input:
        return "You can ask me about time, weather, or just say hello!"

    # Farewell
    elif "bye" in user_input or "exit" in user_input:
        return "Goodbye! Have a great day!"

    # Default response
    else:
        return "I'm not sure I understand that. Could you rephrase it?"


# Main loop
print("Chatbot: Hello! Type 'bye' to exit.")

while True:
    user = input("You: ")
    response = chatbot_response(user)
    print("Chatbot:", response)

    if "bye" in user.lower() or "exit" in user.lower():
        break