# -*- coding: utf-8 -*-
"""Artificial_Intelligence_Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9XOPkvvzRXnzF5i24vvPqRecRjOtzER
"""

from typing import List, Optional, Tuple
import random

# Placeholder functions to make the script runnable
def new_board() -> List[str]:
    return [' '] * 9

def print_board(board: List[str]):
    print('\n------------')
    for i in range(0, 9, 3):
        print(f' {board[i]} | {board[i+1]} | {board[i+2]}')
        if i < 6:
            print('---+---+---')
    print('------------\n')

def winner(board: List[str]) -> Optional[str]:
    win_conditions = [
        (0, 1, 2), (3, 4, 5), (6, 7, 8),  # Rows
        (0, 3, 6), (1, 4, 7), (2, 5, 8),  # Columns
        (0, 4, 8), (2, 4, 6)             # Diagonals
    ]
    for a, b, c in win_conditions:
        if board[a] == board[b] == board[c] and board[a] != ' ':
            return board[a]
    return None

def game_over(board: List[str]) -> bool:
    return winner(board) is not None or ' ' not in board

def get_ai_move(board: List[str], ai_player: str, human_player: str) -> int:
    # This is a placeholder for the actual Minimax + Alpha-Beta AI.
    # For now, it just picks a random available move.
    available_moves = [i for i, cell in enumerate(board) if cell == ' ']
    if available_moves:
        return random.choice(available_moves)
    return -1 # Should not happen if game_over is checked


def human_move(board: List[str]) -> int:
    moves = [i for i, cell in enumerate(board) if cell == ' ']
    while True:
        try:
            s = input(f"Your move ({', '.join(str(m+1) for m in moves)}): ").strip()
            if s.lower() in ('q', 'quit', 'exit'):
                print('Exiting...')
                raise SystemExit
            pos = int(s) - 1
            if pos in moves:
                return pos
            else:
                print('Invalid move - cell is taken or out of range.')
        except ValueError:
            print('Please enter a number between 1 and 9 (or q to quit).')


def choose_markers() -> Tuple[str, str]:
    while True:
        choice = input("Choose your marker (X/O) [X]: ").strip().upper()
        if choice == '':
            return ('X', 'O')
        if choice in ('X', 'O'):
            human = choice
            ai = 'O' if human == 'X' else 'X'
            return (human, ai)
        print('Please enter X or O.')


def choose_who_starts() -> str:
    while True:
        choice = input("Who starts? (me/ai) [me]: ").strip().lower()
        if choice == '':
            return 'me'
        if choice in ('me', 'ai'):
            return choice
        print('Please type "me" or "ai".')


def main():
    print('Tic-Tac-Toe — Unbeatable AI (Minimax + Alpha-Beta)')
    board = new_board()
    human_player, ai_player = choose_markers()
    starter = choose_who_starts()


    current = 'me' if starter == 'me' else 'ai'
    print(f'You are {human_player}. AI is {ai_player}. {"You" if current=="me" else "AI"} start.')


    while True:
        print_board(board)


        if game_over(board):
            break


        if current == 'me':
            move = human_move(board)
            board[move] = human_player
            current = 'ai'
        else:
            print('AI is thinking...')
            move = get_ai_move(board, ai_player, human_player)
            board[move] = ai_player
            current = 'me'


    print_board(board)
    w = winner(board)
    if w == human_player:
        print('Congratulations — you win!')
    elif w == ai_player:
        print('AI wins. Better luck next time!')
    else:
        print("It's a draw.")




if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('\nInterrupted. Goodbye!')